### ISSUE TITLE
setState同步状态

### ISSUE THREAD

**Issue by classLfz** [classLfz/gomoku-react#1]
因为`setState`的异步问题，导致人为点击落子后，AI立马执行判断并下子函数，从而导致输赢判断函数的状态不是最新的状态，而判断失误。

**Comment by classLfz** [comment]
使用redux解决了该问题。

**Comment by SapiensSuwan** [comment]
您好，我下载了您的code，但是还是不能解决判断输赢的问题，请问您知道我需要做什么修改来实现判断输赢这个功能吗？谢谢。

**Comment by classLfz** [comment]
你好，能告知一下运行环境吗？因为判断输赢本身就已经是实现了的，可能是跟你的运行环境有关？有没有什么报错之类的？

**Comment by classLfz** [comment]
@SapiensSuwan 你好，能告知一下运行环境吗？因为判断输赢本身就已经是实现了的，可能是跟你的运行环境有关？有没有什么报错之类的？

**Comment by SapiensSuwan** [comment]
我下载了您的code然后用VS Code打开运行的。我的电脑版本是macOS 10.14.4 (18E226)。React版本是react-native@0.59.8 | MIT | deps: 50 | versions: 300。我打开http://localhost:3000/的inspect没有看到报错信息... 麻烦你了！

**Comment by classLfz** [comment]
@SapiensSuwan 我觉得这中间是不是有什么误会？你有严格按照我在readme里边执行的流程吗？因为我这个项目是react + redux，并没有使用到 react-native。

**Comment by SapiensSuwan** [comment]
sorry这几天没看电脑，我今天再试试，麻烦你了。

**Comment by SapiensSuwan** [comment]
> @SapiensSuwan 我觉得这中间是不是有什么误会？你有严格按照我在readme里边执行的流程吗？因为我这个项目是react + redux，并没有使用到 react-native。

Sorry.. 我检查了一下，没有问题，是我搞错了，不好意思打扰你了。
